
MAPPINGS = {"/" => {template: "index",
                    title: nil},

            "/sharing" => {template: "sharing/index",
                           title: "What happens when I share my photo? : "},
            "/sharing/how_do_i_share" => {template: "sharing/how_do_i_share",
                           title: "How do I share a photo : What happens when I share my photo? : "},

            "/sharing/clicking_a_link" => {template: "sharing/clicking_a_link",
                                           title: "What happens when someone clicks my shared link? : What happens when I share my photo? : "},

            "/sharing/broken_links" => {template: "sharing/broken_links",
                           title: "Why doesn't a link work>? : What happens when I share my photo? : "},

            "/sharing/links_look_different" => {template: "sharing/links_look_different",
                           title: "Why does a link look different on the page? : What happens when I share my photo? : "},

            "/upload" => {template: "upload/index",
                           title: "What happens when I upload my photo? : "},
            "/upload/what_is_sent" => {template: "upload/what_is_sent",
                                       title: "What is sent? : Uploading a photo : "},

            "/upload/where_is_it_sent" => {template: "upload/where_is_it_sent",
                                       title: "Where is it sent? : Uploading a photo : "},

            "/upload/how_is_it_sent" => {template: "upload/how_is_it_sent",
                                       title: "How is it sent : Uploading a photo : "},

                                       "/upload/when_the_internet_breaks" => {template: "upload/when_the_internet_breaks",
                                       title: "When the internet breaks : Uploading a photo : "},

            "/privacy_security" => {template: "privacy_security/index",
                                    title: "Security and Privacy : "},
            "/privacy_security/security" => {template: "privacy_security/security/index",
                                             title: "Security : Security and Privacy : "},
            "/privacy_security/security/transmission" => {template: "privacy_security/security/transmission",
                                                      title: "Transmission : Security : Security and Privacy : "},
            "/privacy_security/security/access" => {template: "privacy_security/security/access",
                                                            title: "Access : Security : Security and Privacy : "},
            "/privacy_security/security/storage" => {template: "privacy_security/security/storage",
                                                           title: "Storage : Security : Security and Privacy : "},
            "/privacy_security/privacy" => {template: "privacy_security/privacy/index",
                                            title: "Privacy : Security and Privacy : "},
            "/privacy_security/privacy/what" => {template: "privacy_security/privacy/what",
                                                 title: "What information you show : Privacy : Security and Privacy : "},
            "/privacy_security/privacy/who" => {template: "privacy_security/privacy/who",
                                                title: "Who you show information to : Privacy : Security and Privacy : "},
            "/privacy_security/privacy/how" => {template: "privacy_security/privacy/how",
                                                title: "How you show information : Privacy : Security and Privacy : "},
            "/privacy_security/privacy/where" => {template: "privacy_security/privacy/where",
                                                  title: "Where you show information : Privacy : Security and Privacy : "},
             "/privacy_security/privacy/when" => {template: "privacy_security/privacy/when",
                                                  title: "When you show information : Privacy : Security and Privacy : "},
             "/privacy_security/privacy/breaches" => {template: "privacy_security/privacy/breaches/index",
                                                      title: "Privacy breaches : Privacy : Security and Privacy : "},
             "/privacy_security/privacy/breaches/revealing_too_much" => {template: "privacy_security/privacy/breaches/revealing_too_much",
                                                                         title: "Revealing more than intended : Privacy breaches : Privacy : Security and Privacy : "},
             "/privacy_security/privacy/breaches/permissions" => {template: "privacy_security/privacy/breaches/permissions",
                                                                  title: "Taking without permission : Privacy breaches : Privacy : Security and Privacy : "},
             "/privacy_security/privacy/breaches/software" => {template: "privacy_security/privacy/breaches/software",
                                                               title: "Badly designed software : Privacy breaches : Privacy : Security and Privacy : "},
}
